require: rubocop-rspec

Metrics/LineLength:
    Max: 99
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
RSpec/NotToNot:
  EnforcedStyle: 'to_not'
RSpec/ExpectChange:
  EnforcedStyle: 'block'
AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'public/**/*'
