require: rubocop-rspec

Metrics/LineLength:
    Max: 99
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'public/**/*'
