defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/ruby:2.6.0-node-browsers
      environment:
        PGHOST: 127.0.0.1
        PGUSER: home_budget
    - image: circleci/postgres:12.1-alpine-ram
      environment:
        POSTGRES_USER: home_budget

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  bundle_install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: gem install bundler
      - restore-cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save-cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/repo/vendor/bundle

  run_unit_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore-cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle config
          command: bundle config --local path ~/repo/vendor/bundle
      - run: RAILS_ENV=test bundle exec rake db:create db:schema:load --trace
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

workflows:
  version: 2

  build-and-test:
    jobs:
      - checkout_code
      - bundle_install:
          requires:
            - checkout_code
      - run_unit_tests:
          requires:
            - bundle_install
